# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 354197c3c87fbe51dd522326675a23bb291764f3f58ca64ca6998a3a8931eb2a21752e1535dfe76e4b3b3faf176e9b0e234daeb7557bea2ca484ab2c36f2d708

test:
  secret_key_base: 4014d685b2d6ca7b6ec6b144dde38cfb3b5402806f83e26a412bf2f192b347c4047798e92724f1730c36d5a708d46bb27bb45a5d9f086d421a1f3205c4e0dee0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
